spring:
  application:
    name: xiaohongshu-mcp-server
  main:
    web-application-type: none

  ai:
    mcp:
      server:
        enabled: true
        stdio: true
        name: ${spring.application.name}
        version: 1.0.0

# 小红书 API 配置
xhs:
  api:
    cookie: ${XHS_API_COOKIE:}

logging:
  pattern:
    console:
  level:
    root: WARN
